"""Tests for slicer module."""

import json

import pytest

from fabprint.slicer import SLICER_PATHS, _apply_overrides, find_slicer, parse_gcode_stats


def test_find_bambu():
    if not SLICER_PATHS["bambu"].exists():
        pytest.skip("BambuStudio not installed")
    assert find_slicer("bambu") == SLICER_PATHS["bambu"]


def test_find_orca():
    if not SLICER_PATHS["orca"].exists():
        pytest.skip("OrcaSlicer not installed")
    assert find_slicer("orca") == SLICER_PATHS["orca"]


def test_find_unknown():
    with pytest.raises(ValueError, match="Unknown slicer"):
        find_slicer("cura")


def test_apply_overrides():
    data = {
        "wall_loops": 2,
        "sparse_infill_density": "15%",
        "other_setting": "keep",
    }

    result = _apply_overrides(data, {
        "wall_loops": 4,
        "sparse_infill_density": "25%",
    }, "test_profile")

    try:
        written = json.loads(result.read_text())
        assert written["wall_loops"] == "4"
        assert written["sparse_infill_density"] == "25%"
        assert written["other_setting"] == "keep"
        assert "inherits" not in written
    finally:
        result.unlink(missing_ok=True)


def test_parse_gcode_stats_full(tmp_path):
    gcode = tmp_path / "plate.gcode"
    gcode.write_text(
        "; HEADER_BLOCK_START\n"
        "; generated by OrcaSlicer\n"
        "; estimated printing time (normal mode) = 1h 33m 15s\n"
        "; HEADER_BLOCK_END\n"
        "G28 ; home\n"
        "G1 X10 Y10\n"
        "; filament used [mm] = 14395.62\n"
        "; filament used [cm3] = 34.63\n"
        "; filament used [g] = 42.94\n"
        "; total filament used [g] = 42.94\n"
    )
    stats = parse_gcode_stats(tmp_path)
    assert stats["filament_g"] == 42.94
    assert stats["print_time"] == "1h 33m 15s"


def test_parse_gcode_stats_orca_format(tmp_path):
    """OrcaSlicer 2.3+ format: time in header, cm3 in footer, no grams."""
    gcode = tmp_path / "plate.gcode"
    gcode.write_text(
        "; model printing time: 4m 23s; total estimated time: 10m 52s\n"
        "; filament_density: 0\n"
        "G28 ; home\n"
        "G1 X10 Y10\n"
        "; filament used [mm] = 101.51\n"
        "; filament used [cm3] = 0.24\n"
    )
    stats = parse_gcode_stats(tmp_path)
    assert stats["filament_cm3"] == 0.24
    assert stats["print_time"] == "10m 52s"
    assert "filament_g" not in stats


def test_parse_gcode_stats_empty(tmp_path):
    assert parse_gcode_stats(tmp_path) == {}


def test_parse_gcode_stats_no_metadata(tmp_path):
    gcode = tmp_path / "plate.gcode"
    gcode.write_text("G28 ; home\nG1 X10 Y10\n")
    assert parse_gcode_stats(tmp_path) == {}
